application: testapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: testapp.wsgi.application

skip_files:
- ^google_appengine*
- ^submodules*
- ^(.*/)?.*\.py[co]
